In [21]:
import pandas as pd
import numpy as np

In [30]:
def ready_up():
    df = pd.read_csv("/home/mohe/Desktop/esm_famil_data.csv")
    df = df.applymap(lambda x: str(x).replace(" ",""))
    return df

In [40]:
df = ready_up()
dfa = dict()
def add_participant(name, answer):
    global dfa
    dfa = pd.DataFrame(dfa)
    dfa = dfa.applymap(lambda x: str(x).replace(" ", ""))
    dfa[name] = answer
    print(dfa)

    
    
    # unique = ((dfa[col] == (y[col])).sum() == 1)

    

# dfa["score"] = 0
 
    # df_a = pd.DataFrame([answer])
    # df_a.index = [name]
    # dfa = pd.concat([dfa, df_a])


add_participant('salib', {'esm': 'بردیا', 'famil': 'بابایی', 'keshvar': 'باربادوس', 'rang': 'بنفش', 'ashia': 'بمب', 'ghaza': 'باقالیپلو'})
add_participant('kianoush', {'esm': 'بهرام', 'famil': 'بهرامی', 'keshvar': 'برزیل', 'rang': 'بلوطی', 'ashia': 'بیل', 'ghaza': 'به   پلو'})
add_participant('sajjad', {'esm': 'بابک', 'famil': 'بهشتی', 'keshvar': 'باهاما', 'rang': 'بژ', 'ashia': '        ', 'ghaza': 'برنج خورشت'})
add_participant('farhad', {'esm': 'بهرام', 'famil': 'براتی', 'keshvar': 'بببببب', 'rang': 'بژ', 'ashia': 'بیل', 'ghaza': 'باقلوا'})
dfa = dfa.T
dfa = dfa.applymap(lambda x: None if str(x).strip() == "" else x)


def compute_scores(row):
    col_list = dfa.columns
    score = 0
    for col in col_list:
        print(row[col], type(row[col]))
        if pd.notna(row[col]) or row[col] == 'None':
            count = (dfa[col] == row[col]).sum()
            if count == 1 and row[col] in df[col].values:
                score += 15 if dfa[col].isnull().any() else 10
            elif count > 1 and row[col] in df[col].values:
                score += 10 if dfa[col].isnull().any() else 5
        
    return score
dfa

             salib
esm          بردیا
famil       بابایی
keshvar   باربادوس
rang          بنفش
ashia          بمب
ghaza    باقالیپلو
             salib  kianoush
esm          بردیا     بهرام
famil       بابایی    بهرامی
keshvar   باربادوس     برزیل
rang          بنفش     بلوطی
ashia          بمب       بیل
ghaza    باقالیپلو  به   پلو
             salib kianoush      sajjad
esm          بردیا    بهرام        بابک
famil       بابایی   بهرامی       بهشتی
keshvar   باربادوس    برزیل      باهاما
rang          بنفش    بلوطی          بژ
ashia          بمب      بیل
ghaza    باقالیپلو    بهپلو  برنج خورشت
             salib kianoush     sajjad  farhad
esm          بردیا    بهرام       بابک   بهرام
famil       بابایی   بهرامی      بهشتی   براتی
keshvar   باربادوس    برزیل     باهاما  بببببب
rang          بنفش    بلوطی         بژ      بژ
ashia          بمب      بیل                بیل
ghaza    باقالیپلو    بهپلو  برنجخورشت  باقلوا

            esm   famil   keshvar   rang ashia      ghaza
salib     بردیا  بابایی  باربادوس   بنفش   بمب  باقالیپلو
kianoush  بهرام  بهرامی     برزیل  بلوطی   بیل      بهپلو
sajjad     بابک   بهشتی    باهاما     بژ  None  برنجخورشت
farhad    بهرام   براتی    بببببب     بژ   بیل     باقلوا

In [43]:
def calculate():
    
    dfa['score'] = dfa.apply(compute_scores, axis=1)

calculate()
    # for col in col_list:
    #     not_none = (dfa[col].isnull().any())
    #     dfa['score'] = dfa.applymap(lambda y: y['score'] if y[col] == None else (y['score'] + 15 if ((dfa[col] == (y[col])).sum() == 1) and not(not_none)
    #                              else (y['score'] + 10 if ((((dfa[col] == (y[col])).sum() == 1) and not_none) or (not not_none and not((dfa[col] == (y[col])).sum() == 1)))
    #                              else (y['score'] + 5 if not((dfa[col] == (y[col])).sum() == 1) and not_none else y['score']))), axis = 1)
    # # dfa[col] = dfa.apply(lambda y: y[col] if y[col] in (df[col]).values else None, axis = 1)
    #     dfa['score'] = dfa.apply(lambda y: y['score'] - 10 if y[col] in (df[col]) else y['score'])

UnboundLocalError: local variable 'dfa' referenced before assignment

In [42]:
dfa

            esm   famil   keshvar   rang ashia      ghaza  score
salib     بردیا  بابایی  باربادوس   بنفش   بمب  باقالیپلو     65
kianoush  بهرام  بهرامی     برزیل  بلوطی   بیل      بهپلو     55
sajjad     بابک   بهشتی    باهاما     بژ  None  برنجخورشت     45
farhad    بهرام   براتی    بببببب     بژ   بیل     باقلوا     40