In [1]:
import pandas as pd

In [3]:
df = pd.read_sas('BMX_J.XPT')

In [4]:
df

,SEQN,BMDSTATS,BMXWT,BMIWT,BMXRECUM,BMIRECUM,BMXHEAD,BMIHEAD,BMXHT,BMIHT,...,BMXLEG,BMILEG,BMXARML,BMIARML,BMXARMC,BMIARMC,BMXWAIST,BMIWAIST,BMXHIP,BMIHIP
0,93703.0,1.0,13.7,3.0,89.6,NaN,NaN,NaN,88.6,NaN,...,NaN,NaN,18.0,NaN,16.2,NaN,48.2,NaN,NaN,NaN
1,93704.0,1.0,13.9,NaN,95.0,NaN,NaN,NaN,94.2,NaN,...,NaN,NaN,18.6,NaN,15.2,NaN,50.0,NaN,NaN,NaN
2,93705.0,1.0,79.5,NaN,NaN,NaN,NaN,NaN,158.3,NaN,...,37.0,NaN,36.0,NaN,32.0,NaN,101.8,NaN,110.0,NaN
3,93706.0,1.0,66.3,NaN,NaN,NaN,NaN,NaN,175.7,NaN,...,46.6,NaN,38.8,NaN,27.0,NaN,79.3,NaN,94.4,NaN
4,93707.0,1.0,45.4,NaN,NaN,NaN,NaN,NaN,158.4,NaN,...,38.1,NaN,33.8,NaN,21.5,NaN,64.1,NaN,83.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8699,102952.0,1.0,49.0,NaN,NaN,NaN,NaN,NaN,156.5,NaN,...,34.4,NaN,32.6,NaN,25.1,NaN,82.2,NaN,87.3,NaN
8700,102953.0,1.0,97.4,NaN,NaN,NaN,NaN,NaN,164.9,NaN,...,38.2,NaN,36.6,NaN,40.6,NaN,114.8,NaN,112.8,NaN
8701,102954.0,1.0,69.1,NaN,NaN,NaN,NaN,NaN,162.6,NaN,...,39.2,NaN,35.2,NaN,26.8,NaN,86.4,NaN,102.7,NaN
8702,102955.0,1.0,111.9,NaN,NaN,NaN,NaN,NaN,156.6,NaN,...,39.2,NaN,35.0,NaN,44.5,NaN,113.5,NaN,128.3,NaN
8703,102956.0,1.0,111.5,NaN,NaN,NaN,NaN,NaN,175.8,NaN,...,42.5,NaN,38.0,NaN,40.0,NaN,122.0,NaN,110.0,NaN

In [8]:
df.isnull().any()

SEQN        False
BMDSTATS    False
BMXWT        True
BMIWT        True
BMXRECUM     True
BMIRECUM     True
BMXHEAD      True
BMIHEAD      True
BMXHT        True
BMIHT        True
BMXBMI       True
BMXLEG       True
BMILEG       True
BMXARML      True
BMIARML      True
BMXARMC      True
BMIARMC      True
BMXWAIST     True
BMIWAIST     True
BMXHIP       True
BMIHIP       True
dtype: bool

In [13]:
df.columns.nunique()

21

In [17]:
pip install -U scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 2.2 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01m
Collecting scipy>=1.5.0
  Downloading scipy-1.11.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.4/36.4 MB 2.7 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.2.0-py3-none-any.whl (15 kB)
Collecting joblib>=1.1.1
  Downloading joblib-1.3.2-py3-none-any.whl (302 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.2/302.2 KB 3.5 MB/s eta 0:00:00[36m0:00:01[36m0:00:01
Requirement already satisfied: numpy<2.0,>=1.17.3 in /home/ubuntu/Machine Learning Bootcamp/ML Basic/ML_Basic_venv/lib/python3.10/site-packages (from scikit-learn) (1.26.2)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.3.2 scikit-learn-1.3.2 scipy-1.11.4 threadpoolctl-3.2.0
Note: you may need to restart the kernel to use updated packages.

In [26]:
null_percent = df.isnull().mean()

In [31]:
null_percent

SEQN        0.000000
BMDSTATS    0.000000
BMXWT       0.014246
BMIWT       0.952206
BMXRECUM    0.897289
BMIRECUM    0.997243
BMXHEAD     0.977711
BMIHEAD     1.000000
BMXHT       0.079044
BMIHT       0.988626
BMXBMI      0.080308
BMXLEG      0.229894
BMILEG      0.961627
BMXARML     0.060547
BMIARML     0.960133
BMXARMC     0.061006
BMIARMC     0.959789
BMXWAIST    0.126723
BMIWAIST    0.949793
BMXHIP      0.306181
BMIHIP      0.968980
dtype: float64

In [18]:
from sklearn.cluster import KMeans

In [40]:
from seaborn import sns

ImportError: cannot import name 'sns' from 'seaborn' (/home/ubuntu/Machine Learning Bootcamp/ML Basic/ML_Basic_venv/lib/python3.10/site-packages/seaborn/__init__.py)

In [23]:
intended_cols = [col for col in df.columns if col[2]!='I']

In [32]:
df_rev = df[intended_cols]

In [36]:
find_row_null = df_rev.isna().sum(axis = 1)

In [37]:
sns.histplot(find_row_null)

<bound method hist_series of 0       3
1       3
2       2
3       2
4       2
       ..
8699    2
8700    2
8701    2
8702    2
8703    2
Length: 8704, dtype: int64>

In [33]:
df_last = df_rev.drop(['SEQN'], axiz = 1)

,SEQN,BMDSTATS,BMXWT,BMXRECUM,BMXHEAD,BMXHT,BMXBMI,BMXLEG,BMXARML,BMXARMC,BMXWAIST,BMXHIP
0,93703.0,1.0,13.7,89.6,NaN,88.6,17.5,NaN,18.0,16.2,48.2,NaN
1,93704.0,1.0,13.9,95.0,NaN,94.2,15.7,NaN,18.6,15.2,50.0,NaN
2,93705.0,1.0,79.5,NaN,NaN,158.3,31.7,37.0,36.0,32.0,101.8,110.0
3,93706.0,1.0,66.3,NaN,NaN,175.7,21.5,46.6,38.8,27.0,79.3,94.4
4,93707.0,1.0,45.4,NaN,NaN,158.4,18.1,38.1,33.8,21.5,64.1,83.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8699,102952.0,1.0,49.0,NaN,NaN,156.5,20.0,34.4,32.6,25.1,82.2,87.3
8700,102953.0,1.0,97.4,NaN,NaN,164.9,35.8,38.2,36.6,40.6,114.8,112.8
8701,102954.0,1.0,69.1,NaN,NaN,162.6,26.1,39.2,35.2,26.8,86.4,102.7
8702,102955.0,1.0,111.9,NaN,NaN,156.6,45.6,39.2,35.0,44.5,113.5,128.3
8703,102956.0,1.0,111.5,NaN,NaN,175.8,36.1,42.5,38.0,40.0,122.0,110.0

In [ ]:
df_last = df_last.drop(['BMXRECUM', ''], axiz = 1)

In [ ]:
from sklearn.impute import SimpleImputer
import numpy as np


# To calculate mean use imputer class
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X)

X_rev = imputer.transform(intended_cols)
print(X_rev)