<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=6 color=#F32500>
        <div  align=center>
            تمرین هفته دوم بوت کمپ یادگیری ماشین-
            مپصا
        </div>
        <br/>
    </font>
</div>

<div style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<div align=center>
			<font face="IranNastaliq" size=5>    
                  چون عهده نمی‌شود کسی فردا را
                <br><br>
                 حالی خوش دار این دل پر سودا را
                <br><br>
                می نوش به ماهتاب ای ماه که ماه
                <br><br>
                بسیار بتابد و نیابد ما را        			   	
                <p></p>
			</font>
        </div>
    </font>
</div>

In [2]:
import numpy as np
import pandas as pd
import ast

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال اول:‌
        </font>
در این تمرین قصد داریم به تحلیل داده های فیلم های برتر سینمای جهان به معیار imdb بپردازیم. ابتدا دادههای مربوط به فیلم را از فایل csv فراخوانی میکنیم
        <br/>
    </font>
</div>

In [3]:
movies = pd.read_csv("/home/gemmara/Downloads/imdb_movie_rank.csv")
movies.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [4]:
movies.describe()

       star_rating    duration
count   979.000000  979.000000
mean      7.889785  120.979571
std       0.336069   26.218010
min       7.400000   64.000000
25%       7.600000  102.000000
50%       7.800000  117.000000
75%       8.100000  134.000000
max       9.300000  242.000000

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
        در این دیتاست اگر داده ای وجود دارد که مقدار nullدارد سطرش را حذف کنید. 
        <br/>
    </font>
</div>

In [5]:
rows_with_null = movies[movies.isna().any(axis=1)]

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
        فیلم ها را براساس مدت زمان فیلم به صورت نزولی مرتب کنید و پنجاه تای اول را در فایل csv با نام long_time ذخیره کنید 
        <br/>
    </font>
</div>

In [6]:
movies.sort_values('duration', ascending=False, inplace=True)
movies.iloc[:50, :].to_csv('long_time.csv')

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
         تابعی بنویسید که نام بازیگر را به عنوان آرگومان بگیرد و تعداد فیلم های برتر از این لیست را که بازی کرده محاسبه کند.
        <br/>
    </font>
</div>

In [30]:
movies['actors_list'] = movies['actors_list'].apply(lambda x: ', '.join(x))

def get_movies_count(actor_name):    
    filtered_movies = movies[movies['actors_list'].str.contains(actor_name, case=False, na=False)]
    return filtered_movies.shape[0]

get_movies_count('Morgan freeman')

0

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
         میانگین امتیاز فیلم ها را براساس ژانر نمایش به دست آورید.
        <br/>
    </font>
</div>

In [35]:
movies['mean_rating'] = movies.groupby(['genre']).star_rating.transform('mean')
movies

,star_rating,title,content_rating,genre,duration,actors_list,mean_rating
476,7.8,Hamlet,PG-13,Drama,242,"K, e, n, n, e, t, h, , B, r, a, n, a, g, h, ,...",7.902518
157,8.2,Gone with the Wind,G,Drama,238,"C, l, a, r, k, , G, a, b, l, e, ,, , V, i, v...",7.902518
78,8.4,Once Upon a Time in America,R,Crime,229,"R, o, b, e, r, t, , D, e, , N, i, r, o, ,, ...",7.916935
142,8.3,Lagaan: Once Upon a Time in India,PG,Adventure,224,"A, a, m, i, r, , K, h, a, n, ,, , G, r, a, c...",7.933333
445,7.9,The Ten Commandments,APPROVED,Adventure,220,"C, h, a, r, l, t, o, n, , H, e, s, t, o, n, ,...",7.933333
...,...,...,...,...,...,...,...
293,8.1,Duck Soup,PASSED,Comedy,68,"G, r, o, u, c, h, o, , M, a, r, x, ,, , H, a...",7.822436
88,8.4,The Kid,NOT RATED,Comedy,68,"C, h, a, r, l, e, s, , C, h, a, p, l, i, n, ,...",7.822436
258,8.1,The Cabinet of Dr. Caligari,UNRATED,Crime,67,"W, e, r, n, e, r, , K, r, a, u, s, s, ,, , C...",7.916935
338,8.0,Battleship Potemkin,UNRATED,History,66,"A, l, e, k, s, a, n, d, r, , A, n, t, o, n, o...",8.000000
389,8.0,Freaks,UNRATED,Drama,64,"W, a, l, l, a, c, e, , F, o, r, d, ,, , L, e...",7.902518

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
       ستونی به این داده ها اضافه کنید که در صورت اینکه یک فیلم مدت نمایش آن 150 دقیقه و یا بیشتر بود مقدار صفر و در غیر اینصورت 1 در هر سطر این ستون قرار گیرد. دیتافریم حاصل را در یک فایل csv ذخیره کنید.
        <br/>
    </font>
</div>

In [48]:
movies['duration_bool'] = (movies['duration'] >= 150).astype(int)
movies.to_csv('movies_with_duratio_bool.csv')
movies

,star rating,title,content rating,genre,duration,actors list,mean rating,duration bool,duration_bool
476,7.8,Hamlet,PG-13,Drama,242,"K, e, n, n, e, t, h, , B, r, a, n, a, g, h, ,...",7.902518,1,1
157,8.2,Gone with the Wind,G,Drama,238,"C, l, a, r, k, , G, a, b, l, e, ,, , V, i, v...",7.902518,1,1
78,8.4,Once Upon a Time in America,R,Crime,229,"R, o, b, e, r, t, , D, e, , N, i, r, o, ,, ...",7.916935,1,1
142,8.3,Lagaan: Once Upon a Time in India,PG,Adventure,224,"A, a, m, i, r, , K, h, a, n, ,, , G, r, a, c...",7.933333,1,1
445,7.9,The Ten Commandments,APPROVED,Adventure,220,"C, h, a, r, l, t, o, n, , H, e, s, t, o, n, ,...",7.933333,1,1
...,...,...,...,...,...,...,...,...,...
293,8.1,Duck Soup,PASSED,Comedy,68,"G, r, o, u, c, h, o, , M, a, r, x, ,, , H, a...",7.822436,0,0
88,8.4,The Kid,NOT RATED,Comedy,68,"C, h, a, r, l, e, s, , C, h, a, p, l, i, n, ,...",7.822436,0,0
258,8.1,The Cabinet of Dr. Caligari,UNRATED,Crime,67,"W, e, r, n, e, r, , K, r, a, u, s, s, ,, , C...",7.916935,0,0
338,8.0,Battleship Potemkin,UNRATED,History,66,"A, l, e, k, s, a, n, d, r, , A, n, t, o, n, o...",8.000000,0,0
389,8.0,Freaks,UNRATED,Drama,64,"W, a, l, l, a, c, e, , F, o, r, d, ,, , L, e...",7.902518,0,0

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
        عنوان ستونها را به نحوی تغییر دهید که در ستون های دارای _(آندرلاین) فاصله قرار گیرد. به عنوان مثال star_rating به star rating تبدیل می شود.
        <br/>
    </font>
</div>

In [41]:
movies.columns = movies.columns.str.replace('_', ' ')
movies

,star rating,title,content rating,genre,duration,actors list,mean rating,duration bool
476,7.8,Hamlet,PG-13,Drama,242,"K, e, n, n, e, t, h, , B, r, a, n, a, g, h, ,...",7.902518,1
157,8.2,Gone with the Wind,G,Drama,238,"C, l, a, r, k, , G, a, b, l, e, ,, , V, i, v...",7.902518,1
78,8.4,Once Upon a Time in America,R,Crime,229,"R, o, b, e, r, t, , D, e, , N, i, r, o, ,, ...",7.916935,1
142,8.3,Lagaan: Once Upon a Time in India,PG,Adventure,224,"A, a, m, i, r, , K, h, a, n, ,, , G, r, a, c...",7.933333,1
445,7.9,The Ten Commandments,APPROVED,Adventure,220,"C, h, a, r, l, t, o, n, , H, e, s, t, o, n, ,...",7.933333,1
...,...,...,...,...,...,...,...,...
293,8.1,Duck Soup,PASSED,Comedy,68,"G, r, o, u, c, h, o, , M, a, r, x, ,, , H, a...",7.822436,0
88,8.4,The Kid,NOT RATED,Comedy,68,"C, h, a, r, l, e, s, , C, h, a, p, l, i, n, ,...",7.822436,0
258,8.1,The Cabinet of Dr. Caligari,UNRATED,Crime,67,"W, e, r, n, e, r, , K, r, a, u, s, s, ,, , C...",7.916935,0
338,8.0,Battleship Potemkin,UNRATED,History,66,"A, l, e, k, s, a, n, d, r, , A, n, t, o, n, o...",8.000000,0
389,8.0,Freaks,UNRATED,Drama,64,"W, a, l, l, a, c, e, , F, o, r, d, ,, , L, e...",7.902518,0

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
        داده ها را براساس ژانر گروه بندی و مرتب کنید و از هر ژانر صرفا سه تای برتر را نمایش دهید
        <br/>
    </font>
</div>

In [46]:
movies.groupby('genre').apply(lambda each_group: each_group.sort_values('star rating')[:3])

               star rating                                            title  \
genre
Action    976          7.4  Master and Commander: The Far Side of the World
          967          7.4                                         The Rock
          954          7.4                                            X-Men
Adventure 937          7.4                                        Labyrinth
          936          7.4                                        True Grit
          953          7.4                            The NeverEnding Story
Animation 938          7.4                              Alice in Wonderland
          966          7.4                               The Simpsons Movie
          835          7.5                                  Despicable Me 2
Biography 964          7.4                                          Lincoln
          930          7.4                                  Man on the Moon
          961          7.4                                           Capote
Comedy    956          7.4                         Manhattan Murder Mystery
          949          7.4                                       Home Alone
          960          7.4                                 The Way Way Back
Crime     978          7.4                                      Wall Street
          969          7.4                              Law Abiding Citizen
          931          7.4                                     Mean Streets
Drama     968          7.4                              The English Patient
          958          7.4                               My Sister's Keeper
          939          7.4                                   Predestination
Family    497          7.8              Willy Wonka & the Chocolate Factory
          468          7.9                       E.T. the Extra-Terrestrial
Fantasy   638          7.7                        The City of Lost Children
Film-Noir 687          7.7                                       Spellbound
          210          8.1                                            Laura
          105          8.3                                    The Third Man
History   338          8.0                              Battleship Potemkin
Horror    977          7.4                                      Poltergeist
          869          7.5                        A Nightmare on Elm Street
          905          7.5                                          Dracula
Mystery   965          7.4                                        Limitless
          863          7.5                         Three Days of the Condor
          866          7.5                                 To Catch a Thief
Sci-Fi    637          7.7                             The Butterfly Effect
          484          7.8                    The Day the Earth Stood Still
          408          7.9                                          Gravity
Thriller  848          7.5                        The Man Who Knew Too Much
          902          7.5                                           Frenzy
          728          7.6                               La piel que habito
Western   704          7.6                              High Plains Drifter
          421          7.9                           The Outlaw Josey Wales
          263          8.1                                        Rio Bravo

              content rating      genre  duration  \
genre
Action    976          PG-13     Action       138
          967              R     Action       136
          954          PG-13     Action       104
Adventure 937             PG  Adventure       101
          936            NaN  Adventure       128
          953             PG  Adventure       102
Animation 938              G  Animation        75
          966          PG-13  Animation        87
          835             PG  Animation        98
Biography 964          PG-13  Biography       150
          930              R  Biography       118
          961              R  Biography       114
Comedy    956             PG     Comedy       104
          949             PG     Comedy       103
          960          PG-13     Comedy       103
Crime     978              R      Crime       126
          969              R      Crime       109
          931              R      Crime       112
Drama     968              R      Drama       162
          958          PG-13      Drama       109
          939              R      Drama        97
Family    497              G     Family       100
          468             PG     Family       115
Fantasy   638              R    Fantasy       112
Film-Noir 687        UNRATED  Film-Noir       111
          210       APPROVED  Film-Noir        88
          105      NOT RATED  Film-Noir        93
History   338        UNRATED    History        66
Horror    977             PG     Horror       114
          869              R     Horror        91
          905              R     Horror       128
Mystery   965          PG-13    Mystery       105
          863              R    Mystery       117
          866       APPROVED    Mystery       106
Sci-Fi    637              R     Sci-Fi       113
          484       APPROVED     Sci-Fi        92
          408          PG-13     Sci-Fi        91
Thriller  848             PG   Thriller       120
          902              R   Thriller       116
          728              R   Thriller       120
Western   704              R    Western       105
          421             PG    Western       135
          263      NOT RATED    Western       141

                                                     actors list  mean rating  \
genre
Action    976  R, u, s, s, e, l, l,  , C, r, o, w, e, ,,  , P...     7.884559
          967  S, e, a, n,  , C, o, n, n, e, r, y, ,,  , N, i...     7.884559
          954  P, a, t, r, i, c, k,  , S, t, e, w, a, r, t, ,...     7.884559
Adventure 937  D, a, v, i, d,  , B, o, w, i, e, ,,  , J, e, n...     7.933333
          936  J, o, h, n,  , W, a, y, n, e, ,,  , K, i, m,  ...     7.933333
          953  N, o, a, h,  , H, a, t, h, a, w, a, y, ,,  , B...     7.933333
Animation 938  K, a, t, h, r, y, n,  , B, e, a, u, m, o, n, t...     7.914516
          966  D, a, n,  , C, a, s, t, e, l, l, a, n, e, t, a...     7.914516
          835  S, t, e, v, e,  , C, a, r, e, l, l, ,,  , K, r...     7.914516
Biography 964  D, a, n, i, e, l,  , D, a, y, -, L, e, w, i, s...     7.862338
          930  J, i, m,  , C, a, r, r, e, y, ,,  , D, a, n, n...     7.862338
          961  P, h, i, l, i, p,  , S, e, y, m, o, u, r,  , H...     7.862338
Comedy    956  W, o, o, d, y,  , A, l, l, e, n, ,,  , D, i, a...     7.822436
          949  M, a, c, a, u, l, a, y,  , C, u, l, k, i, n, ,...     7.822436
          960  S, t, e, v, e,  , C, a, r, e, l, l, ,,  , T, o...     7.822436
Crime     978  C, h, a, r, l, i, e,  , S, h, e, e, n, ,,  , M...     7.916935
          969  G, e, r, a, r, d,  , B, u, t, l, e, r, ,,  , J...     7.916935
          931  R, o, b, e, r, t,  , D, e,  , N, i, r, o, ,,  ...     7.916935
Drama     968  R, a, l, p, h,  , F, i, e, n, n, e, s, ,,  , J...     7.902518
          958  C, a, m, e, r, o, n,  , D, i, a, z, ,,  , A, b...     7.902518
          939  E, t, h, a, n,  , H, a, w, k, e, ,,  , S, a, r...     7.902518
Family    497  G, e, n, e,  , W, i, l, d, e, r, ,,  , J, a, c...     7.850000
          468  H, e, n, r, y,  , T, h, o, m, a, s, ,,  , D, r...     7.850000
Fantasy   638  R, o, n,  , P, e, r, l, m, a, n, ,,  , D, a, n...     7.700000
Film-Noir 687  I, n, g, r, i, d,  , B, e, r, g, m, a, n, ,,  ...     8.033333
          210  G, e, n, e,  , T, i, e, r, n, e, y, ,,  , D, a...     8.033333
          105  O, r, s, o, n,  , W, e, l, l, e, s, ,,  , J, o...     8.033333
History   338  A, l, e, k, s, a, n, d, r,  , A, n, t, o, n, o...     8.000000
Horror    977  J, o, B, e, t, h,  , W, i, l, l, i, a, m, s, ,...     7.806897
          869  H, e, a, t, h, e, r,  , L, a, n, g, e, n, k, a...     7.806897
          905  G, a, r, y,  , O, l, d, m, a, n, ,,  , W, i, n...     7.806897
Mystery   965  B, r, a, d, l, e, y,  , C, o, o, p, e, r, ,,  ...     7.975000
          863  R, o, b, e, r, t,  , R, e, d, f, o, r, d, ,,  ...     7.975000
          866  C, a, r, y,  , G, r, a, n, t, ,,  , G, r, a, c...     7.975000
Sci-Fi    637  A, s, h, t, o, n,  , K, u, t, c, h, e, r, ,,  ...     7.920000
          484  M, i, c, h, a, e, l,  , R, e, n, n, i, e, ,,  ...     7.920000
          408  S, a, n, d, r, a,  , B, u, l, l, o, c, k, ,,  ...     7.920000
Thriller  848  J, a, m, e, s,  , S, t, e, w, a, r, t, ,,  , D...     7.680000
          902  J, o, n,  , F, i, n, c, h, ,,  , B, a, r, r, y...     7.680000
          728  A, n, t, o, n, i, o,  , B, a, n, d, e, r, a, s...     7.680000
Western   704  C, l, i, n, t,  , E, a, s, t, w, o, o, d, ,,  ...     8.255556
          421  C, l, i, n, t,  , E, a, s, t, w, o, o, d, ,,  ...     8.255556
          263  J, o, h, n,  , W, a, y, n, e, ,,  , D, e, a, n...     8.255556

               duration bool
genre
Action    976              0
          967              0
          954              0
Adventure 937              0
          936              0
          953              0
Animation 938              0
          966              0
          835              0
Biography 964              1
          930              0
          961              0
Comedy    956              0
          949              0
          960              0
Crime     978              0
          969              0
          931              0
Drama     968              1
          958              0
          939              0
Family    497              0
          468              0
Fantasy   638              0
Film-Noir 687              0
          210              0
          105              0
History   338              0
Horror    977              0
          869              0
          905              0
Mystery   965              0
          863              0
          866              0
Sci-Fi    637              0
          484              0
          408              0
Thriller  848              0
          902              0
          728              0
Western   704              0
          421              0
          263              0