<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=6 color=#F32500>
        <div  align=center>
            تمرین هفته دوم بوت کمپ یادگیری ماشین-
            مپصا
        </div>
        <br/>
    </font>
</div>

<div style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<div align=center>
			<font face="IranNastaliq" size=5>    
                  چون عهده نمی‌شود کسی فردا را
                <br><br>
                 حالی خوش دار این دل پر سودا را
                <br><br>
                می نوش به ماهتاب ای ماه که ماه
                <br><br>
                بسیار بتابد و نیابد ما را        			   	
                <p></p>
			</font>
        </div>
    </font>
</div>

In [101]:
%config IPCompleter.use_jedi=False

In [25]:
import numpy as np
import pandas as pd

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال اول:‌
        </font>
در این تمرین قصد داریم به تحلیل داده های فیلم های برتر سینمای جهان به معیار imdb بپردازیم. ابتدا دادههای مربوط به فیلم را از فایل csv فراخوانی میکنیم
        <br/>
    </font>
</div>

In [116]:
movies = pd.read_csv("data/imdb_movie_rank.csv")
movies.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [27]:
movies.describe()

       star_rating    duration
count   979.000000  979.000000
mean      7.889785  120.979571
std       0.336069   26.218010
min       7.400000   64.000000
25%       7.600000  102.000000
50%       7.800000  117.000000
75%       8.100000  134.000000
max       9.300000  242.000000

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
        در این دیتاست اگر داده ای وجود دارد که مقدار nullدارد سطرش را حذف کنید. 
        <br/>
    </font>
</div>

In [7]:
#TODO
movies.dropna()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
        فیلم ها را براساس مدت زمان فیلم به صورت نزولی مرتب کنید و پنجاه تای اول را در فایل csv با نام long_time ذخیره کنید 
        <br/>
    </font>
</div>

In [30]:
#TODO
movies.sort_values('duration',ascending=False)

movies.head(50).to_csv('./dunp_50.csv')

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
         تابعی بنویسید که نام بازیگر را به عنوان آرگومان بگیرد و تعداد فیلم های برتر از این لیست را که بازی کرده محاسبه کند.
        <br/>
    </font>
</div>

In [21]:
#TODO
def count_actor_movies(actor:str) -> int:
    return movies.actors_list.str.count(actor).sum()
count_actor_movies('Al Pacino')

13

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
         میانگین امتیاز فیلم ها را براساس ژانر نمایش به دست آورید.
        <br/>
    </font>
</div>

In [47]:
#TODO
movies.star_rating.sum()/movies.genre.count()

movies.groupby("genre").agg(rating=("star_rating", "mean")).sort_values('rating',ascending=False)

             rating
genre
Western    8.255556
Film-Noir  8.033333
History    8.000000
Mystery    7.975000
Adventure  7.933333
Sci-Fi     7.920000
Crime      7.916935
Animation  7.914516
Drama      7.902518
Action     7.884559
Biography  7.862338
Family     7.850000
Comedy     7.822436
Horror     7.806897
Fantasy    7.700000
Thriller   7.680000

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
       ستونی به این داده ها اضافه کنید که در صورت اینکه یک فیلم مدت نمایش آن 150 دقیقه و یا بیشتر بود مقدار صفر و در غیر اینصورت 1 در هر سطر این ستون قرار گیرد. دیتافریم حاصل را در یک فایل csv ذخیره کنید.
        <br/>
    </font>
</div>

In [58]:
#TODO
movies['more_150_min'] = movies['duration'].apply(lambda x: x>=150)
movies.to_csv('./long_movies.csv')

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
        عنوان ستونها را به نحوی تغییر دهید که در ستون های دارای _(آندرلاین) فاصله قرار گیرد. به عنوان مثال star_rating به star rating تبدیل می شود.
        <br/>
    </font>
</div>

In [66]:
#TODO
movies.columns = movies.columns.str.replace('_',' ')
movies

,star rating,title,content rating,genre,duration,actors list,more 150 min
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...",False
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']",True
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv...",True
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E...",True
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L....",True
...,...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G...",False
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma...",False
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo...",False
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr...",False
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar...",False

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
        داده ها را براساس ژانر گروه بندی و مرتب کنید و از هر ژانر صرفا سه تای برتر را نمایش دهید
        <br/>
    </font>
</div>

In [80]:
#TODO
# movies.sort_values(['genre','star rating'],ascending=[1,0]).groupby('genre')['star rating'].nlargest(3)
movies.sort_values(['genre','star rating'],ascending=[1,0]).groupby('genre').apply(lambda x: x.nlargest(3, 'star rating'))

               star rating                                              title  \
genre
Action    3            9.0                                    The Dark Knight
          11           8.8                                          Inception
          12           8.8     Star Wars: Episode V - The Empire Strikes Back
Adventure 7            8.9      The Lord of the Rings: The Return of the King
          10           8.8  The Lord of the Rings: The Fellowship of the Ring
          14           8.8              The Lord of the Rings: The Two Towers
Animation 30           8.6                                      Spirited Away
          55           8.5                                      The Lion King
          61           8.5                             Grave of the Fireflies
Biography 8            8.9                                   Schindler's List
          18           8.7                                         Goodfellas
          31           8.6                                   The Intouchables
Comedy    25           8.6                                  Life Is Beautiful
          29           8.6                                        City Lights
          35           8.6                                       Modern Times
Crime     0            9.3                           The Shawshank Redemption
          1            9.2                                      The Godfather
          2            9.1                             The Godfather: Part II
Drama     5            8.9                                       12 Angry Men
          9            8.9                                         Fight Club
          13           8.8                                       Forrest Gump
Family    468          7.9                         E.T. the Extra-Terrestrial
          497          7.8                Willy Wonka & the Chocolate Factory
Fantasy   638          7.7                          The City of Lost Children
Film-Noir 105          8.3                                      The Third Man
          210          8.1                                              Laura
          687          7.7                                         Spellbound
History   338          8.0                                Battleship Potemkin
Horror    39           8.6                                             Psycho
          57           8.5                                              Alien
          62           8.5                                        The Shining
Mystery   38           8.6                                        Rear Window
          46           8.5                                            Memento
          76           8.4                                            Vertigo
Sci-Fi    145          8.2                                       Blade Runner
          321          8.0                                             Brazil
          408          7.9                                            Gravity
Thriller  350          8.0                                  Shadow of a Doubt
          496          7.8                                             Misery
          728          7.6                                 La piel que habito
Western   6            8.9                     The Good, the Bad and the Ugly
          26           8.6                       Once Upon a Time in the West
          59           8.5                                   Django Unchained

              content rating      genre  duration  \
genre
Action    3            PG-13     Action       152
          11           PG-13     Action       148
          12              PG     Action       124
Adventure 7            PG-13  Adventure       201
          10           PG-13  Adventure       178
          14           PG-13  Adventure       179
Animation 30              PG  Animation       125
          55               G  Animation        89
          61         UNRATED  Animation        89
Biography 8                R  Biography       195
          18               R  Biography       146
          31               R  Biography       112
Comedy    25           PG-13     Comedy       116
          29          PASSED     Comedy        87
          35               G     Comedy        87
Crime     0                R      Crime       142
          1                R      Crime       175
          2                R      Crime       200
Drama     5        NOT RATED      Drama        96
          9                R      Drama       139
          13           PG-13      Drama       142
Family    468             PG     Family       115
          497              G     Family       100
Fantasy   638              R    Fantasy       112
Film-Noir 105      NOT RATED  Film-Noir        93
          210       APPROVED  Film-Noir        88
          687        UNRATED  Film-Noir       111
History   338        UNRATED    History        66
Horror    39               R     Horror       109
          57               R     Horror       117
          62               R     Horror       146
Mystery   38        APPROVED    Mystery       112
          46               R    Mystery       113
          76        APPROVED    Mystery       128
Sci-Fi    145              R     Sci-Fi       117
          321              R     Sci-Fi       132
          408          PG-13     Sci-Fi        91
Thriller  350       APPROVED   Thriller       108
          496              R   Thriller       107
          728              R   Thriller       120
Western   6        NOT RATED    Western       161
          26           PG-13    Western       175
          59               R    Western       165

                                                     actors list  more 150 min
genre
Action    3    [u'Christian Bale', u'Heath Ledger', u'Aaron E...          True
          11   [u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'...         False
          12   [u'Mark Hamill', u'Harrison Ford', u'Carrie Fi...         False
Adventure 7    [u'Elijah Wood', u'Viggo Mortensen', u'Ian McK...          True
          10   [u'Elijah Wood', u'Ian McKellen', u'Orlando Bl...          True
          14   [u'Elijah Wood', u'Ian McKellen', u'Viggo Mort...          True
Animation 30   [u'Daveigh Chase', u'Suzanne Pleshette', u'Miy...         False
          55   [u'Matthew Broderick', u'Jeremy Irons', u'Jame...         False
          61   [u'Tsutomu Tatsumi', u'Ayano Shiraishi', u'Ake...         False
Biography 8    [u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings...          True
          18    [u'Robert De Niro', u'Ray Liotta', u'Joe Pesci']         False
          31   [u'Fran\xe7ois Cluzet', u'Omar Sy', u'Anne Le ...         False
Comedy    25   [u'Roberto Benigni', u'Nicoletta Braschi', u'G...         False
          29   [u'Charles Chaplin', u'Virginia Cherrill', u'F...         False
          35   [u'Charles Chaplin', u'Paulette Goddard', u'He...         False
Crime     0    [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...         False
          1      [u'Marlon Brando', u'Al Pacino', u'James Caan']          True
          2    [u'Al Pacino', u'Robert De Niro', u'Robert Duv...          True
Drama     5    [u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...         False
          9    [u'Brad Pitt', u'Edward Norton', u'Helena Bonh...         False
          13     [u'Tom Hanks', u'Robin Wright', u'Gary Sinise']         False
Family    468  [u'Henry Thomas', u'Drew Barrymore', u'Peter C...         False
          497  [u'Gene Wilder', u'Jack Albertson', u'Peter Os...         False
Fantasy   638  [u'Ron Perlman', u'Daniel Emilfork', u'Judith ...         False
Film-Noir 105  [u'Orson Welles', u'Joseph Cotten', u'Alida Va...         False
          210  [u'Gene Tierney', u'Dana Andrews', u'Clifton W...         False
          687  [u'Ingrid Bergman', u'Gregory Peck', u'Michael...         False
History   338  [u'Aleksandr Antonov', u'Vladimir Barsky', u'G...         False
Horror    39   [u'Anthony Perkins', u'Janet Leigh', u'Vera Mi...         False
          57   [u'Sigourney Weaver', u'Tom Skerritt', u'John ...         False
          62   [u'Jack Nicholson', u'Shelley Duvall', u'Danny...         False
Mystery   38   [u'James Stewart', u'Grace Kelly', u'Wendell C...         False
          46   [u'Guy Pearce', u'Carrie-Anne Moss', u'Joe Pan...         False
          76   [u'James Stewart', u'Kim Novak', u'Barbara Bel...         False
Sci-Fi    145  [u'Harrison Ford', u'Rutger Hauer', u'Sean You...         False
          321  [u'Jonathan Pryce', u'Kim Greist', u'Robert De...         False
          408  [u'Sandra Bullock', u'George Clooney', u'Ed Ha...         False
Thriller  350  [u'Teresa Wright', u'Joseph Cotten', u'Macdona...         False
          496  [u'James Caan', u'Kathy Bates', u'Richard Farn...         False
          728  [u'Antonio Banderas', u'Elena Anaya', u'Jan Co...         False
Western   6    [u'Clint Eastwood', u'Eli Wallach', u'Lee Van ...          True
          26   [u'Henry Fonda', u'Charles Bronson', u'Claudia...          True
          59   [u'Jamie Foxx', u'Christoph Waltz', u'Leonardo...          True

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال دوم:‌
        </font>
        تفاوت بین متد read_table و read_csv در ماژول pandas چیست؟
        <br/>
    </font>
</div>

#TODO
The read_csv parameter 'parse_dates' is false, for read_table it is the opposite
read_csv default separator is ',' but for read_table is 'tab-stop'

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال سوم:‌
        </font>
        با استفاده از متد value_counts تعداد فیلمها در هر ریت محتوا را به دست آورید.
        <br/>
    </font>
</div>

In [92]:
movies['content rating'].value_counts()

content rating
R            460
PG-13        189
PG           123
NOT RATED     65
APPROVED      47
UNRATED       38
G             32
PASSED         7
NC-17          7
X              4
GP             3
TV-MA          1
Name: count, dtype: int64

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال چهارم:‌
        </font>
       توضیح دهید crosstab در پانداس چه میکند و عملکرد آنرا بر روی کد زیر توضیح دهید؟
        <br/>
    </font>
</div>

In [ ]:
pd.crosstab(movies.genre, movies.content_rating)

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال پنچم:‌
        </font>
         توضیح دهید متد corr در پانداس چه میکند و عملکرد آنرا بر روی کد زیر توضیح دهید؟ 
        <br/>
    </font>
</div>

In [99]:
movies.corr(method='pearson', min_periods=200, numeric_only=True)

              star rating  duration  more 150 min
star rating      1.000000  0.227149      0.221328
duration         0.227149  1.000000      0.744894
more 150 min     0.221328  0.744894      1.000000

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال ششم:‌
        </font>
        با استفاده از متد sample هفتاد و پنج درصد سطرها را در یک متغیر به نام sample_1 بریزید. درنهایت با استفاده از متد drop از دیتافریم اصلی این سطرها را حذف و دیتافریم جدید را در sample_2 بریزید
        <br/>
    </font>
</div>

In [121]:
#TODO
sample_1 = movies.sample(frac=0.75,replace=False)
sample_2 = movies.drop(index=sample_1.index,inplace=False)
sample_2

,star_rating,title,content_rating,genre,duration,actors_list
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
13,8.8,Forrest Gump,PG-13,Drama,142,"[u'Tom Hanks', u'Robin Wright', u'Gary Sinise']"
19,8.7,Star Wars,PG,Action,121,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
28,8.6,Leon: The Professional,R,Crime,110,"[u'Jean Reno', u'Gary Oldman', u'Natalie Portm..."
30,8.6,Spirited Away,PG,Animation,125,"[u'Daveigh Chase', u'Suzanne Pleshette', u'Miy..."
...,...,...,...,...,...,...
951,7.4,Sleepy Hollow,R,Drama,105,"[u'Johnny Depp', u'Christina Ricci', u'Miranda..."
952,7.4,Pirate Radio,R,Comedy,117,"[u'Philip Seymour Hoffman', u'Bill Nighy', u'N..."
955,7.4,Zero Dark Thirty,R,Drama,157,"[u'Jessica Chastain', u'Joel Edgerton', u'Chri..."
964,7.4,Lincoln,PG-13,Biography,150,"[u'Daniel Day-Lewis', u'Sally Field', u'David ..."
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال هفتم:‌
        </font>
         متد pivot_table چه عملکردی دارد؟
        <br/>
    </font>
</div>

In [137]:
#TODO
pd.pivot_table(sample_1, values='star_rating', index=pd.cut(sample_1['star_rating'], bins=bins), aggfunc='mean')
pd.pivot_table(sample_1, values='star_rating', index=pd.cut(sample_1['star_rating'], bins=bins), aggfunc='count')

             star_rating
star_rating
(7.4, 7.9]           401
(7.9, 8.4]           246
(8.4, 8.9]            47

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال هشتم برای خودم:‌
        </font>
         ساب کنید در هر بازه امتیاز چه تعداد فیلم وجود دارد
        <br/>
    </font>
</div>

In [88]:
bins = pd.interval_range(start=movies['star rating'].min(), end=movies['star rating'].max(), freq=0.5)

# شمارش تعداد اعضا در هر بازه
counts = pd.cut(movies['star rating'], bins=bins).value_counts()
counts

star rating
(7.4, 7.9]    536
(7.9, 8.4]    331
(8.4, 8.9]     59
Name: count, dtype: int64